version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - yarn install --production --ignore-scripts --prefer-offline
      - yarn run build
      - zip -r deploy/lambda.zip dist/ node_modules
      - aws cloudformation package --template-file sam-template.yml --s3-bucket $DEPLOY_BUCKET --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - sam-template.yml
    - outputtemplate.yaml